apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: project-b  
  labels:
    tier: application
spec:
  containers:
  - name: my-app-container
    image: nginx:latest
    ports:
    - containerPort: 8080
