apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: project-a
  labels:
    tier: db  
spec:
  containers:
  - name: mysql-container
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Random-P@a$12"
    ports:
    - containerPort: 3306

